import { z } from "zod";

export const ERROR_CODES = [
  "VALIDATION_ERROR",
  "AUTH_REQUIRED",
  "FORBIDDEN",
  "CONTENT_LOCKED",
  "NOT_FOUND",
  "CONTENT_UNAVAILABLE",
  "STALE_WRITE",
  "SOURCE_ISBN_TAKEN",
  "SERIES_SOURCE_DUPLICATE",
  "SLUG_LOCKED",
  "SLUG_CONFLICT",
  "ASSET_IN_USE",
  "REPLACE_CONFIRMATION_REQUIRED",
  "REQUIRED_FOR_PUBLISHED",
  "PARENT_IN_TRASH",
  "AUDIO_CHANGED",
  "MEDIA_NOT_UPLOADED",
  "SERIES_NOT_PUBLISHABLE",
  "EPISODE_NOT_PUBLISHABLE",
  "EPISODE_ORDER_MISMATCH",
  "SERIES_SOURCE_ORDER_MISMATCH",
  "MEDIA_TYPE_NOT_ALLOWED",
  "MEDIA_TOO_LARGE",
  "MEDIA_INVALID",
  "PROGRESS_INVALID",
  "IDEMPOTENCY_KEY_REQUIRED",
  "IDEMPOTENCY_REQUEST_IN_PROGRESS",
  "IDEMPOTENCY_KEY_REUSED",
  "RATE_LIMITED",
  "MEDIA_PROVIDER_UNAVAILABLE",
  "BAD_REQUEST",
  "PAYLOAD_TOO_LARGE",
  "CONFLICT",
  "CONTENT_IN_TRASH",
  "INVALID_STATE_TRANSITION",
  "SERVICE_UNAVAILABLE",
  "INTERNAL_SERVER_ERROR",
  "HTTP_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const RETRYABLE_ERROR_CODES = [
  "SLUG_CONFLICT",
  "RATE_LIMITED",
  "MEDIA_PROVIDER_UNAVAILABLE",
] as const satisfies readonly ErrorCode[];

export const ErrorResponseSchema = z.object({
  error_code: z.enum(ERROR_CODES),
  message: z.string(),
});

export type ErrorResponse = z.infer<typeof ErrorResponseSchema>;
